sudo: false
language: node_js
node_js:
- 6
cache:
  directories:
    - node_modules
    - node_cache
branches:
  only:
    - source
env:
  global:
  - GH_REF: github.com/kamranayub/kamranayub.github.io.git
  - WYAM_VERSION: v0.15.8-beta
addons:
  apt:
    packages:
      - unzip
before_install:
- mkdir wyam
install:
- unzip tools/Wyam-${WYAM_VERSION}.zip -d wyam
script:
- npm run build_ci
after_success:
- chmod ugo+x deploy.sh
- '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || ./deploy.sh'